function config($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('head_Page');
	$stateProvider
		.state('head_Page',{
			url:'/head_Page',
			templateUrl:'views/head_Page.html',
			controller:"refresh",
			controller:"swiper",
			data:{
				title:"首页"
			}
		})
		.state('tuijian_Page',{
			url:'/tuijian_Page',
			templateUrl:'views/tuijian_Page.html',
			controller:"refresh",
			controller:"swiper",
			data:{
				title:"推荐页"
			}
		})
		.state('need_Page',{
			url:'/need_Page',
			templateUrl:'views/need_Page.html',
			data:{
				title:"个人需求页"
			}
		})
		.state('tuangou_Page',{
			url:'/tuangou_Page',
			templateUrl:'views/tuangou_Page.html',
			controller:"refresh",
			data:{
				title:"团购页"
			}
		})
		.state('list_Page',{
			url:'/list_Page',
			templateUrl:'views/list_Page.html',
			controller:"refresh",
			data:{
				title:"列表页"
			}
		})
		.state('mycatch_Page',{
			url:'/mycatch_Page',
			templateUrl:'views/mycatch_Page.html',
			controller:"refresh",
			data:{
				title:"我的缓存页"
			}
		})
		.state('zuce_Page',{
			url:'/zuce_Page',
			templateUrl:'views/zuce_Page.html',
			data:{
				title:"注册页"
			}
		})
		.state('login_Page',{
			url:'/login_Page',
			templateUrl:'views/login_Page.html',
			controller:"sub",
			data:{
				title:"登录页"
			}
		})
		.state('country_Page',{
			url:'/country_Page',
			templateUrl:'views/country_Page.html',
			controller:"refresh",
			data:{
				title:"国家页"
			}
		})
		.state('persondata_Page',{
			url:'/persondata_Page',
			templateUrl:'views/persondata_Page.html',
			data:{
				title:"个人资料页"
			}
		})
		.state('address_Page',{
			url:'/address_Page',
			templateUrl:'views/address_Page.html',
			data:{
				title:"地址页"
			}
		})
		.state('tuangou2_Page',{
			url:'/tuangou2_Page',
			templateUrl:'views/tuangou2_Page.html',
			controller:"refresh",
			data:{
				title:"团购页2"
			}
		})
}

angular.module("myApp")
	.config(config);